// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Platform      FirebaseOptions
/// web           defaultWeb
/// android       android
///
/// To populate [FirebaseOptions.requireToSignIn] usage, follow the guide here:
/// https://firebase.google.com/docs/auth/digital-identity-verification

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAywzY-1T6RDn3A5ni4wyR0Er4pCT2cSE4',
    appId: '1:627429253742:web:f94d3d73aa2ae862783c7f',
    messagingSenderId: '627429253742',
    projectId: 'studenthub-3606b',
    authDomain: 'studenthub-3606b.firebaseapp.com',
    storageBucket: 'studenthub-3606b.firebasestorage.app',
    measurementId: 'G-ZNNMXLVRWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEdqeDDch1Eb4xRZyMd9rBPGJrCtuXKu4',
    appId: '1:627429253742:android:fec3469ebee4ea2d783c7f',
    messagingSenderId: '627429253742',
    projectId: 'studenthub-3606b',
    storageBucket: 'studenthub-3606b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxj7e2uJyZFspi9RRe6SMr8O48lzSYti4',
    appId: '1:627429253742:ios:5720a7c79ab6fdf5783c7f',
    messagingSenderId: '627429253742',
    projectId: 'studenthub-3606b',
    storageBucket: 'studenthub-3606b.firebasestorage.app',
    iosBundleId: 'com.example.studentHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxj7e2uJyZFspi9RRe6SMr8O48lzSYti4',
    appId: '1:627429253742:ios:5720a7c79ab6fdf5783c7f',
    messagingSenderId: '627429253742',
    projectId: 'studenthub-3606b',
    storageBucket: 'studenthub-3606b.firebasestorage.app',
    iosBundleId: 'com.example.studentHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAywzY-1T6RDn3A5ni4wyR0Er4pCT2cSE4',
    appId: '1:627429253742:web:ae82049b83725094783c7f',
    messagingSenderId: '627429253742',
    projectId: 'studenthub-3606b',
    authDomain: 'studenthub-3606b.firebaseapp.com',
    storageBucket: 'studenthub-3606b.firebasestorage.app',
    measurementId: 'G-6EQQ8V3T2N',
  );

}